dist: xenial
language: python
sudo: false
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
env:
 - DJANGO='django>=1.11,<2.0'
 - DJANGO='django>=2.0,<2.1'
 - DJANGO='django>=2.1,<2.2'
 - DJANGO='django>=2.2a1,<3.0'
install:
 - pip install $DJANGO django-classy-tags pep8 backport-collections
script: python runtests.py
notifications:
  email: false
matrix:
  exclude:
    - python: 2.7
      env: DJANGO='django>=2.0,<2.1'
    - python: 2.7
      env: DJANGO='django>=2.1,<2.2'
    - python: 2.7
      env: DJANGO='django>=2.2a1,<3.0'
    - python: 3.4
      env: DJANGO='django>=2.1,<2.2'
    - python: 3.4
      env: DJANGO='django>=2.2a1,<3.0'
